server:
  port: 1111
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
    #服务续约任务的调用时间间隔为30秒
    lease-renewal-interval-in-seconds: 30
    #服务失效时间为90秒
    lease-expiration-duration-in-seconds: 90
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:1112/eureka
